# Generated by Django 4.1.4 on 2023-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0006_alter_userdetail_uphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
