# Generated by Django 4.1.4 on 2023-02-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
