# Generated by Django 4.1.4 on 2023-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
    ]
